AirPortMaintananceProject/AirportMaintenanceSystemProject/Controllers/AirportItemController.cs
using AirportMaintenanceSystemProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AirportMaintenanceSystemProject.Controllers
{
    [Authorize]
    public class AirportItemController : Controller
    {

        AirportMaintenanceSystemEntities context = new AirportMaintenanceSystemEntities();
        // Action Method which will return the View containing list of Items
        public ActionResult ItemList()
        {
            var listofData = context.Items.ToList();
            return View(listofData);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult AddNewItem()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult AddNewItem(Item model)
        {
            context.Items.Add(model);
            context.SaveChanges();
            ViewBag.Message = "Data Insert Successfully";
            return View();
        }
        [HttpGet]
        public ActionResult UpdateItemDetails(int? id)
        {
            var Itemdata = context.Items.Where(x => x.ItemId == id).FirstOrDefault();
            return View(Itemdata);
        }
        [HttpPost]
        public ActionResult UpdateItemDetails(Item Model)
        {
            var Itemdata = context.Items.Where(x => x.ItemId == Model.ItemId).FirstOrDefault();
            if (Itemdata != null)
            {
                Itemdata.ItemId = Model.ItemId;
                Itemdata.ItemName = Model.ItemName;
                Itemdata.ItemCost = Model.ItemCost;

                context.SaveChanges();
            }
            return RedirectToAction("ItemList");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteItemDetails(int id)
        {
            var Itemdata = context.Items.FirstOrDefault(x => x.ItemId == id);
            if (Itemdata != null)
            {
                context.Items.Remove(Itemdata);
                context.SaveChanges();
                return RedirectToAction("ItemList");
            }
            else
                return View();
        }
        public ActionResult ItemDetails(int id)
        {
            var Itemdata = context.Items.Where(x => x.ItemId == id).FirstOrDefault();
            return View(Itemdata);
        }




    }
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Controllers/DashBoardController.cs
using AirportMaintenanceSystemProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AirportMaintenanceSystemProject.Controllers
{
    [Authorize]
    public class DashBoardController : Controller
    {
        AirportMaintenanceSystemEntities context = new AirportMaintenanceSystemEntities();
        public ActionResult DepartmentList()
        {
            var listofData = context.Departments.ToList();
            return View(listofData);

        }

        public ActionResult StaffList()
        {
            var listofData = context.Staffs.ToList();
            return View(listofData);

        }
        public ActionResult AddStaff()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult AddStaff(Staff model)
        {
            context.Staffs.Add(model);
            context.SaveChanges();
            ViewBag.Message = "Data Insert Successfully";
            return View();
        }

        public ActionResult AirportServices()
        {
            return View();
        }
    }
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Controllers/RegisterLoginController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AirportMaintenanceSystemProject.Models;

namespace AirportMaintenanceSystemProject.Controllers
{
    public class RegisterLoginController : Controller
    {
        AirportMaintenanceSystemEntities context = new AirportMaintenanceSystemEntities();



        public ActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignUp(UserLoginRegister userRegister)
        {
            if (ModelState.IsValid)
            {
                context.UserLoginRegisters.Add(userRegister);
                if (context.SaveChanges() > 0)
                {

                    return RedirectToAction("Login");
                }
            }

            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]


        
        public ActionResult Login(UserLoginRegister userLogin, string ReturnUrl)
        {
           
                var user = context.UserLoginRegisters.Where(x => x.UserName == userLogin.UserName && x.Password == userLogin.Password).FirstOrDefault();
                if (user != null)
                {
                    FormsAuthentication.SetAuthCookie(userLogin.UserName, false);


                return RedirectToAction("Dashboard");
               
            }
                else
                {
                ViewData["SuccessMessage"] = "<script>alert('Invalid credential!')</script>";
               

            }
                return View();

            }
        
        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session["username"] = null;
            return Redirect("Login");
        }


    }
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/RegisterLogin/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}
<head>
    <link rel="stylesheet" href="@Url.Content("/Content/DashboardCss.css")" />
</head>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" integrity="sha512-F5QTlBqZlvuBEs9LQPqc1iZv2UMxcVXezbHzomzS6Df4MZMClge/8+gXrKw2fl5ysdk4rWjR0vKS7NNkfymaBQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>"
<
<div class="container">
    <div class="col-lg-3">
        <div class="card" style="width:200px">
            <div class="card-body action">
                
                <h2 style="text-align:center">@Html.ActionLink("Services", "AirportServices", "DashBoard")</h2>
                <div style="text-align:center">

                    <i class="fa fa-wrench"></i>
                    @*<h2 style="text-align:center">20</h2>*@
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="col-lg-3">
        <div class="card" style="width:200px">
            <div class="card-body action">
                <h2 style="text-align:center">@Html.ActionLink("Staffs", "StaffList", "DashBoard")</h2>
                <div style="text-align:center">

                    <i id="icon" class="fa fa-users"></i>

                </div>
            </div>
        </div>
    </div>
</div>
<br />
<br >
<div class="container">
    <div class="col-lg-3">
        <div class="card" style="width:200px">
            <div class="card-body action">
                <h2 style="text-align:center">@Html.ActionLink("Departments", "DepartmentList", "DashBoard")</h2>
                <div style="text-align:center">

                    <i id="icon" class="fa fa-briefcase"></i>

                </div>
            </div>
        </div>
    </div>
</div>
<br/>
<br >
<div class="container">
    <div class="col-lg-3">
        <div class="card" style="width:200px">
            <div class="card-body action">
                <h2 style="text-align:center">@Html.ActionLink("Equipments", "ItemList", "AirportItem")</h2>
                
                <div style="text-align:center">

                    <i id="icon" class="fa fa-tasks"></i>

                </div>
            </div>
        </div>
    </div>
</div>
<br/>
<div class="container"></div>
<div class="container"></div>
<div class="container"></div>
<div class="container"></div>

<div class="Aboutform">
    <h2> About Us--</h2>
    <hr />
    <div class="paragraph">
        <p>
            An airport is an aerodrome with extended facilities, mostly for commercial air transport.[1][2] Airports usually consists of a landing area, which comprises an aerially accessible open space including at least one operationally active surface such as a runway for a plane to take off and to land[3] or a helipad,[4] and often includes adjacent utility buildings such as control towers, hangars[5] and terminals, to maintain and monitor aircraft. Larger airports may have airport aprons, taxiway bridges, air traffic control centres, passenger facilities such as restaurants and lounges, and emergency services. In some countries, the US in particular, airports also typically have one or more fixed-base operators, serving general aviation.

            Operating airports is extremely complicated, with a complex system of aircraft support services, passenger services, and aircraft control services contained within the operation. Thus airports can be major employers, as well as important hubs for tourism and other kinds of transit. Because they are sites of operation for heavy machinery, a number of regulations and safety measures have been implemented in airports, in order to reduce hazards. Additionally, airports have major local environmental impacts, as both large sources of air pollution, noise pollution and other environmental impacts, making them sites that acutely experience the environmental effects of aviation. Airports are also vulnerable infrastructure to extreme weather, climate change caused sea level rise and other disasters.
        </p>
        </div>
    </div>

   

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/RegisterLogin/Login.cshtml
@model AirportMaintenanceSystemProject.Models.UserLoginRegister

@{
    ViewBag.Title = "Login";
}

<head>
    <link rel="stylesheet" href="@Url.Content("/Content/LoginCss.css")" />
</head>

@if (ViewBag.msg != null)
{
    <h2>@ViewBag.msg</h2>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="loginform">
        <h1>Login</h1>
        @*<hr />*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2 lb" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2 lb" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>


        <div>
            <div class="form-group">
                <div class="col-md-offset-3 col-md-10 button">
                    <input type="submit" value="Login" class="btn btn-primary" />
                    @Html.Raw(ViewData["SuccessMessage"])
                    <br /><br />
                    <div class="signuplink">
                        <p>Register Yourself!</p>
                        @Html.ActionLink("SignUp", "SignUp", "RegisterLogin", new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
        <div>
            @*<div class="form-group">
                    <div class="col-md-offset-3 col-md-10">
                        @Html.ActionLink("SignUp", "SignUp", "RegisterLogin", new { @class = "btn btn-primary" })
                    </div>
                </div>*@
        </div>
    </div>
}
<!--<div class="form-group">-->
@*@Html.ActionLink("Sign-Up", "SignUp")*@
<!--@Html.ActionLink("SignUp", "SignUp", "RegisterLogin", new { @class = "btn btn-primary" })
</div>-->



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/RegisterLogin/SignUp.cshtml
@model AirportMaintenanceSystemProject.Models.UserLoginRegister

@{
    ViewBag.Title = "SignUp";
}


<head>
    <link rel="stylesheet" href="@Url.Content("/Content/SignUpCss.css")" />
</head>


@using (Html.BeginForm())
{
    @*@Html.AntiForgeryToken()*@

<div class="form-horizontal">
    <h2>SignUp</h2>

    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
    @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <br /><br />
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <br /><br />
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <br /><br />
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <br /><br />
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <br /> <br />

        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoleId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="SignUp" class="btn btn-primary" />

        </div>
    </div>

    


</div>
              }

<div>
    @Html.ActionLink("Login", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}