AirPortMaintananceProject/AirportMaintenanceSystemProject/Models/Operation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportMaintenanceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operation()
        {
            this.AssignTasks = new HashSet<AssignTask>();
        }
    
        public int OperationId { get; set; }
        public string Subject { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignTask> AssignTasks { get; set; }
    }
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Controllers/OperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using AirportMaintenanceSystemProject.Models;

namespace AirportMaintenanceSystemProject.Controllers
{
    [Authorize]
    public class OperationController : Controller
    {
        AirportMaintenanceSystemEntities context = new AirportMaintenanceSystemEntities();
        // GET: Operations
        public ActionResult OperationList()
        {
            var listofData = context.Operations.ToList();
            return View(listofData);

        }
        [HttpPost]
        public ActionResult Search(string departmentsearch)
        {
            List<Operation> operations = (from o in context.Operations as IEnumerable<Operation>
                                          join d in context.Departments on o.DepartmentId equals d.DepartmentId
                                          where d.DepartmentName == departmentsearch
                                          select new Operation
                                          {

                                              Remarks = o.Remarks,
                                              // Staff = o.Staff,
                                              Subject = o.Subject,
                                              Status = o.Status,
                                              OperationId = o.OperationId
                                          }).ToList();

            return View(operations);

        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult AddNewOperation()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult AddNewOperation(Operation model)
        {
            context.Operations.Add(model);
            context.SaveChanges();
            ViewBag.Message = "Data Insert Successfully";
            return View();
        }
        [HttpGet]
        public ActionResult UpdateOperation(int? id)
        {
            var data = context.Operations.Where(x => x.OperationId == id).FirstOrDefault();
            return View(data);
        }
        [HttpPost]
        public ActionResult UpdateOperation(Operation Model)
        {
            var data = context.Operations.Where(x => x.OperationId == Model.OperationId).FirstOrDefault();
            if (data != null)
            {
                data.OperationId = Model.OperationId;
                data.Subject = Model.Subject;
                data.Status = Model.Status;
                data.Remarks = Model.Remarks;
                data.DepartmentId = Model.DepartmentId;
                data.StaffId = data.StaffId;

                context.SaveChanges();
            }
            return RedirectToAction("OperationList");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteOperation()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteOperation(int id)
        {
            var data = context.Operations.FirstOrDefault(x => x.OperationId == id);
            if (data != null)
            {
                context.Operations.Remove(data);
                context.SaveChanges();
                return RedirectToAction("OperationList");
            }
            else
                return View();
        }
        public ActionResult OperationDetails(int id)
        {
            var data = context.Operations.Where(x => x.OperationId == id).FirstOrDefault();
            return View(data);
        }
        public ActionResult AssignTask()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignTask(int id)
        {
            var Assigndata = context.Operations.FirstOrDefault(x => x.OperationId == id);
            var staffid = Assigndata.StaffId;
            var subject = Assigndata.Subject;

            if (Assigndata != null)
            {
                var Assigndetails = context.Staffs.FirstOrDefault(x => x.StaffId == staffid);

                var staffname = Assigndetails.StaffName;
                AssignTask assigntask = new AssignTask();
                assigntask.Staff = staffname;
                assigntask.Task = subject;
                context.AssignTasks.Add(assigntask);
                context.Operations.Remove(Assigndata);
                context.SaveChanges();
                ViewBag.Message = "Task Assigned Successfully";
                return RedirectToAction("Index");
            }
            else
                return View(Assigndata);
        }






    }
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/Operation/AddNewOperation.cshtml
@model AirportMaintenanceSystemProject.Models.Operation

@{
    ViewBag.Title = "AddNewOperation";
}
<head>
    <link rel="stylesheet" href="@Url.Content("/Content/AddNewOperationCss.css")" />
</head>

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <div class="heading"><h4>Add New Operation</h4></div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <label class="radio-inline">
                @Html.RadioButtonFor(model => model.Status, "Complete", new { @name = "status" })
                Complete
            </label>
            <label class="radio-inline">
                @Html.RadioButtonFor(model => model.Status, "Pending", new { @name = "status" })
                Pending
            </label>
            <label class="radio-inline">
                @Html.RadioButtonFor(model => model.Status, "Working", new { @name = "status" })
                Working
            </label>
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>*@

  

    <div class="form-group">
        @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.StaffId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>


    <div>
        @Html.ActionLink("Back to List", "OperationList")
    </div>

</div>
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/Operation/DeleteOperation.cshtml
@model AirportMaintenanceSystemProject.Models.Operation

@{
    ViewBag.Title = "DeleteOperation";
}

<head>
    <link rel="stylesheet" href="@Url.Content("/Content/Delete.css")" />
</head>
<div class="form-horizontal">
    <div class="heading">
        <h2>DeleteOperation</h2>
        <h3>Are you sure you want to delete this?</h3>
        </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-primary" /> |
                    @Html.ActionLink("Back to List", "OperationList" , new { @class= "btn btn-primary" })
                </div>
            }
        </div>

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/Operation/OperationDetails.cshtml
@model AirportMaintenanceSystemProject.Models.Operation

@{
    ViewBag.Title = "OperationDetails";
}

<h2>OperationDetails</h2>

<div>
    <h4>Operation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StaffId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StaffId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OperationId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/Operation/OperationList.cshtml
@model IEnumerable<AirportMaintenanceSystemProject.Models.Operation>

@{
    ViewBag.Title = "OperationList";
}

<h2>OperationList</h2>
<head>
    <link rel="stylesheet" href="@Url.Content("/Content/MasterCss.css")" />
</head>
<p>
    @using (@Html.BeginForm("Index", "Operations"))
    {
        @Html.TextBox("departmentsearch") <input type="submit" value="search" class="btn btn-primary" />

    }
</p>
<p class="text-right">

    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("AddNewOperation", "AddNewOperation", "Operation", new { @class = "btn btn-primary" })
    }



</p>
@if (ViewBag.Message != null)
{

    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}


@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Remarks)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.DepartmentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StaffId)
            </th>*@
        <th></th>
    </tr>
    @if (Model != null && Model.Count() > 0)
    {
       foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Remarks)
                </td>
               
                <td>
                    @if (User.IsInRole("Manager"))
                        {
                        @Html.ActionLink("UpdateOperation", "UpdateOperation", new { id = item.OperationId }, new { @class = "btn btn-primary" })
                            }
                    @*@Html.ActionLink("Details", "Details", new { id = item.OperationId }) |*@
                    <br /><br />
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("DeleteOperation", "DeleteOperation", new { id = item.OperationId }, new { @class = "btn btn-primary" })
                    }

                    @*@Html.ActionLink("AssignTask", "AssignTask", new { id = item.OperationId }, new { @class = "btn btn-primary" })*@
                </td>
            </tr>
        }
    }
    else
    {
        <td colspan="4" class="text-center"><b>No Data Available . Please Add Data By CLick On Create Button</b></td>

    }
</table>


                

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/Operation/UpdateOperation.cshtml
@model AirportMaintenanceSystemProject.Models.Operation

@{
    ViewBag.Title = "UpdateOperation";
}


<head>
    <link rel="stylesheet" href="@Url.Content("/Content/AddNewOperationCss.css")" />
</head>
@if (ViewBag.Message != null)
{

    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="heading">
        <h4>Update Status And Operation Details</h4>
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.OperationId)

    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <label class="radio-inline">
                @Html.RadioButtonFor(model => model.Status, "Complete", new { @name = "status" })
                Complete
            </label>
            <label class="radio-inline">
                @Html.RadioButtonFor(model => model.Status, "Pending", new { @name = "status" })
                Pending
            </label>
            <label class="radio-inline">
                @Html.RadioButtonFor(model => model.Status, "Working", new { @name = "status" })
                Working
            </label>
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>



    @*<div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StaffId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StaffId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StaffId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "OperationList")
    </div>

</div>
}