AirPortMaintananceProject/AirportMaintenanceSystemProject/Models/Inspection.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace AirportMaintenanceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int InspectionId { get; set; }
        public string Subject { get; set; }
        public string Frequency { get; set; }
        [Required]
        public string Status { get; set; }
        [DataType(DataType.Date)]
       
        public Nullable<System.DateTime> InspectedDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NextDueDate { get; set; }
        public string Review { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Controllers/InspectionController.cs
using AirportMaintenanceSystemProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AirportMaintenanceSystemProject.Controllers
{
    [Authorize]
    public partial class InspectionController : Controller
    {
        AirportMaintenanceSystemEntities context = new AirportMaintenanceSystemEntities();
        // GET: Inspections
        public ActionResult InspectionList()
        {
            var listofData = context.Inspections.ToList();
            return View(listofData);
        }
        [HttpPost]
        public ActionResult InspectionList(string departmentsearch)
        {
            List<Inspection> inspections = (from o in context.Inspections as IEnumerable<Inspection>
                                            join d in context.Departments on o.DepartmentId equals d.DepartmentId
                                            where d.DepartmentName == departmentsearch
                                            select new Inspection
                                            {

                                                Review = o.Review,
                                                // Staff = o.Staff,
                                                Subject = o.Subject,
                                                Status = o.Status,
                                                InspectionId = o.InspectionId
                                            }).ToList();

            return View(inspections);

        }
      
        
       [Authorize(Roles = "Manager")]
        [HttpGet]
        public ActionResult UpdateInspectionDetails(int? id)
        {
            var Inspectiondata= context.Inspections.Where(x => x.InspectionId == id).FirstOrDefault();
            var Statuslist = new List<string>() { "Completed", "Pending", "In-Process" };
            ViewBag.Inspections = Statuslist;
            return View(Inspectiondata);
        }
        [Authorize(Roles = "Manager")]
        [HttpPost]
        public ActionResult UpdateInspectionDetails(Inspection Model)
        {
            var data = context.Inspections.Where(x => x.InspectionId == Model.InspectionId).FirstOrDefault();
            if (data != null)
            {
                data.InspectionId = Model.InspectionId;
                data.Subject = Model.Subject;
                data.Status = Model.Status;
                data.Review = Model.Review;
                data.DepartmentId = Model.DepartmentId;
                data.Frequency = Model.Frequency;
                data.InspectedDate = Model.InspectedDate;
                data.NextDueDate = Model.NextDueDate;

                context.SaveChanges();
            }
            return RedirectToAction("InspectionList");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteInspectionDetails()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteInspectionDetails(int id)
        {
            var data = context.Inspections.FirstOrDefault(x => x.InspectionId == id);
            if (data != null)
            {
                context.Inspections.Remove(data);
                context.SaveChanges();
                return RedirectToAction("InspectionList");
            }
            else
                return View();
        }
        public ActionResult InspectionDetails(int id)
        {
            var data = context.Inspections.Where(x => x.InspectionId == id).FirstOrDefault();
            return View(data);
        }



    }
}

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/Inspection/DeleteInspectionDetails.cshtml
@model AirportMaintenanceSystemProject.Models.Inspection

@{
    ViewBag.Title = "DeleteInspectionDetails";
}
<head>
    <link rel="stylesheet" href="@Url.Content("/Content/Delete.css")" />
</head>
<div class="form-horizontal">
    <div class="heading">
        <h2>DeleteOperation</h2>
        <h3>Are you sure you want to delete this?</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "InspectionList", new { @class = "btn btn-primary" })
        </div>
    }
</div>

@*<head>
        <link rel="stylesheet" href="@Url.Content("/Content/Delete.css")" />
    </head>
    <div class="form-horizontal">
        <div class="heading">
            <h3>Are you sure you want to delete this?</h3>
            </div>
                <hr />
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-primary" /> |
                        @Html.ActionLink("Back to List", "InspectionList")
                    </div>
                }
            </div>*@

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/Inspection/InspectionList.cshtml
@model IEnumerable<AirportMaintenanceSystemProject.Models.Inspection>

@{
    ViewBag.Title = "InspectionList";
}

<h2>InspectionList</h2>
<head>
    <link rel="stylesheet" href="@Url.Content("/Content/MasterCss.css")" />
</head>
<p>
    @using (@Html.BeginForm("InspectionList", "Inspection"))
    {
        @Html.TextBox("departmentsearch") <input type="submit" value="search" class="btn btn-primary" />
    }
</p>
@if (ViewBag.Message != null)
{

    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Frequency)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InspectedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NextDueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Review)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </th>
        <th></th>
    </tr>

    @if (Model != null && Model.Count() > 0)
    {


        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Frequency)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InspectedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NextDueDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Review)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartmentId)
                </td>

                <td>
                    @if (User.IsInRole("Manager"))
                    {
                        @Html.ActionLink("UpdateInspection", "UpdateInspectionDetails", new { id = item.InspectionId }, new { @class = "btn btn-primary" })
                    }
                    <br /><br />
                    @*@Html.ActionLink("Details", "Details", new { id = item.InspectionId }) |*@
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("DeleteInspection", "DeleteInspectionDetails", new { id = item.InspectionId }, new { @class = "btn btn-primary" })
                    }
                    </td>
            </tr>
        }
    }
    else
    {
        <td colspan="4" class="text-center"><b>No Data Available . Please Add Data By CLick On Create Button</b></td>

    }

</table>

AirPortMaintananceProject/AirportMaintenanceSystemProject/Views/Inspection/UpdateInspectionDetails.cshtml
@model AirportMaintenanceSystemProject.Models.Inspection

@{
    ViewBag.Title = "UpdateInspectionDetails";
}
<head>
    <link rel="stylesheet" href="@Url.Content("/Content/UpdateInspection.css")" />
</head>
@if (ViewBag.Message != null)
{

    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="heading">
            <h4>Update Inspections Details</h4>
        </div>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InspectionId)

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Frequency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.Frequency, "Daily", new { @name = "frequency" })
                    Daily
                </label>
                <label class="radio-inline">
                    @Html.RadioButtonFor(model => model.Frequency, "Weekly", new { @name = "frequency" })
                    Weekly
                </label>
                @Html.ValidationMessageFor(model => model.Frequency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, new SelectList(ViewBag.Inspections, "Status"), "select Status")

                @*@Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InspectedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InspectedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InspectedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NextDueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NextDueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NextDueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        <div>
            @Html.ActionLink("Back to List", "InspectionList")
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}